//
// Generated file, do not edit! Created by opp_msgtool 6.1 from WrrPacket.msg.
//

#ifndef __WRRPACKET_M_H
#define __WRRPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class WrrPacket;
/**
 * Class generated from <tt>WrrPacket.msg:2</tt> by opp_msgtool.
 * <pre>
 * message WrrPacket extends cPacket
 * {
 *     int sourceId;
 *     simtime_t creationTime;
 * }
 * </pre>
 */
class WrrPacket : public ::omnetpp::cPacket
{
  protected:
    int sourceId = 0;
    omnetpp::simtime_t creationTime = SIMTIME_ZERO;

  private:
    void copy(const WrrPacket& other);

  protected:
    bool operator==(const WrrPacket&) = delete;

  public:
    WrrPacket(const char *name=nullptr, short kind=0);
    WrrPacket(const WrrPacket& other);
    virtual ~WrrPacket();
    WrrPacket& operator=(const WrrPacket& other);
    virtual WrrPacket *dup() const override {return new WrrPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSourceId() const;
    virtual void setSourceId(int sourceId);

    virtual omnetpp::simtime_t getCreationTime() const;
    virtual void setCreationTime(omnetpp::simtime_t creationTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const WrrPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, WrrPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline WrrPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<WrrPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __WRRPACKET_M_H

